// typst-template.typ
// Main layout template for BusinessReport.
// Reads configuration from _business-report-config.typ (generated by R).

#import "_business-report-config.typ": business-config
#import "cover.typ":      business-cover
#import "back-cover.typ": business-back-cover
#import "toc/toc-classic.typ":   toc-classic
#import "toc/toc-modern.typ":    toc-modern
#import "toc/toc-minimal.typ":   toc-minimal

// ─────────────────────────────────────────────────────────────────────────────
// Unpack configuration
// ─────────────────────────────────────────────────────────────────────────────
#let _font-family   = business-config.at("font-family")
#let _primary-color = business-config.at("primary-color")
#let _toc-style     = business-config.at("toc-style")
#let _show-cover    = business-config.at("cover")
#let _show-back     = business-config.at("back-cover")
#let _lang          = business-config.at("lang")

// ─────────────────────────────────────────────────────────────────────────────
// Colour palette derived from primary
// ─────────────────────────────────────────────────────────────────────────────
#let _light-primary = _primary-color.lighten(80%)
#let _mid-primary   = _primary-color.lighten(40%)
#let _text-dark     = luma(30)
#let _text-muted    = luma(110)
#let _rule-color    = luma(210)

// ─────────────────────────────────────────────────────────────────────────────
// Helper: render authors list
// ─────────────────────────────────────────────────────────────────────────────
#let _render-author(auth) = {
  if type(auth) == dictionary {
    let name = auth.at("name", default: "")
    let aff  = auth.at("affiliation", default: "")
    if aff != "" { [#name · #text(fill: _text-muted, size: 0.85em)[#aff]] }
    else          { [#name] }
  } else {
    [#str(auth)]
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Main template function
// ─────────────────────────────────────────────────────────────────────────────
#let business-report-format(
  title:   "",
  authors: (),
  date:    "",
  body,
) = {

  // ── Page geometry ──────────────────────────────────────────────────────────
  set page(
    paper:  "a4",
    margin: (top: 2.8cm, bottom: 2.8cm, left: 3.2cm, right: 2.5cm),
    numbering:    "1",
    number-align: right,

    // Header: appears from page 2 (after cover or TOC)
    header: context {
      let pg = counter(page).get().first()
      let threshold = if _show-cover { 3 } else { 2 }
      if pg >= threshold {
        set text(size: 8pt, fill: _text-muted)
        grid(
          columns: (1fr, auto),
          align: (left + horizon, right + horizon),
          title,
          counter(page).display("1"),
        )
        v(-0.4em)
        line(length: 100%, stroke: 0.5pt + _rule-color)
      }
    },

    // Footer: minimal, no duplicate page number
    footer: context {
      let pg = counter(page).get().first()
      let threshold = if _show-cover { 3 } else { 2 }
      if pg >= threshold {
        line(length: 100%, stroke: 0.5pt + _rule-color)
        v(-0.3em)
        set text(size: 7.5pt, fill: _text-muted)
        align(right)[#date]
      }
    },
  )

  // ── Typography ─────────────────────────────────────────────────────────────
  set text(
    font:  _font-family,
    size:  11pt,
    fill:  _text-dark,
    lang:  _lang,
  )

  set par(
    justify:    true,
    leading:    0.7em,
    first-line-indent: 1.2em,
  )

  // ── Heading styles ─────────────────────────────────────────────────────────
  set heading(numbering: "1.1")

  // H1 — chapter title: full-width rule, large, colour accent
  show heading.where(level: 1): it => {
    pagebreak(weak: true)
    v(0.8em)
    set text(size: 18pt, weight: "bold", fill: _primary-color)
    block(width: 100%)[
      #grid(
        columns: (0.4cm, 1fr),
        column-gutter: 0.5em,
        rect(width: 100%, height: 100%, fill: _primary-color, radius: 1pt),
        it.body,
      )
    ]
    v(0.3em)
    line(length: 100%, stroke: 1pt + _primary-color)
    v(0.6em)
  }

  // H2 — section: smaller rule, mid colour
  show heading.where(level: 2): it => {
    v(0.7em)
    set text(size: 13.5pt, weight: "bold", fill: _primary-color)
    it.body
    v(0.1em)
    line(length: 40%, stroke: 1pt + _mid-primary)
    v(0.4em)
  }

  // H3 — subsection: no rule, italic-style label
  show heading.where(level: 3): it => {
    v(0.5em)
    set text(size: 11.5pt, weight: "semibold", fill: _text-dark)
    it.body
    v(0.2em)
  }

  // H4 — paragraph heading: inline, no break
  show heading.where(level: 4): it => {
    v(0.3em)
    set text(size: 11pt, weight: "semibold", style: "italic", fill: _text-dark)
    it.body
    [. ]
  }

  // ── Block elements ─────────────────────────────────────────────────────────

  // Tables
  set table(
    stroke:    (x, y) => if y == 0 { (bottom: 1.5pt + _primary-color) }
                         else       { (bottom: 0.5pt + _rule-color) },
    align:     (x, y) => if y == 0 { center } else { left },
    inset:     (x: 0.5em, y: 0.45em),
  )
  show table.header: set text(weight: "bold", fill: _primary-color)

  // Figures: number and caption
  show figure.caption: it => {
    set text(size: 9pt, fill: _text-muted, style: "italic")
    strong[#it.supplement #it.counter.display(it.numbering). ] + it.body
  }

  // Code blocks
  show raw.where(block: true): it => {
    block(
      fill:   luma(248),
      stroke: (left: 3pt + _mid-primary),
      inset:  (x: 1em, y: 0.8em),
      radius: 3pt,
      width:  100%,
      set text(size: 9pt, font: "Fira Code", fill: _text-dark),
      it,
    )
  }
  show raw.where(block: false): set text(size: 9.5pt, fill: _primary-color)

  // Block quotes
  show quote.where(block: true): it => {
    pad(
      left: 1.5em,
      block(
        stroke: (left: 3pt + _mid-primary),
        inset:  (left: 0.8em),
        set text(style: "italic", fill: _text-muted),
        it.body,
      )
    )
  }

  // Links
  show link: it => {
    set text(fill: _primary-color)
    underline(it)
  }

  // ── Document body ──────────────────────────────────────────────────────────

  // 1. Cover page
  if _show-cover {
    business-cover(
      title:        title,
      authors:      authors,
      date:         date,
      primary-color: _primary-color,
      logo-path:    "assets/logo.svg",
    )
    counter(page).update(0)
  }

  // 2. Table of contents (roman page numbering)
  set page(numbering: "i")
  counter(page).update(1)

  if _toc-style == 1 {
    toc-classic(primary-color: _primary-color, font-family: _font-family)
  } else if _toc-style == 2 {
    toc-modern(primary-color: _primary-color, font-family: _font-family)
  } else {
    toc-minimal(primary-color: _primary-color, font-family: _font-family)
  }

  // 3. Main body (arabic page numbering, restart at 1)
  pagebreak()
  set page(numbering: "1")
  counter(page).update(1)

  body

  // 4. Back cover
  if _show-back {
    pagebreak()
    set page(numbering: none, header: none, footer: none)
    business-back-cover(
      primary-color: _primary-color,
      font-family:   _font-family,
    )
  }
}
