# R/utils.R
# Internal utility functions - not exported

# -----------------------------------------------------------------------------
# Path helpers
# -----------------------------------------------------------------------------

#' Return the path to the bundled Quarto extension source
#' @noRd
.ext_source <- function() {
  system.file(
    "quarto", "_extensions", "business-report",
    package = "BusinessReport",
    mustWork = TRUE
  )
}

#' Return the path to the extension inside a user project
#' @noRd
.ext_dest <- function(path) {
  fs::path(path, "_extensions", "business-report")
}

#' Return the path to the config Typst file inside a user project
#' @noRd
.config_typ_path <- function(path) {
  fs::path(.ext_dest(path), "_business-report-config.typ")
}

#' Return the path to the skeleton template
#' @noRd
.skeleton_path <- function() {
  system.file(
    "templates", "skeleton.qmd",
    package = "BusinessReport",
    mustWork = TRUE
  )
}

#' Return the path to the assets template directory
#' @noRd
.assets_source <- function() {
  system.file("templates", "assets", package = "BusinessReport", mustWork = TRUE)
}

#' Return the right-hand value only when the left-hand side is NULL
#' @noRd
`%||%` <- function(x, y) if (is.null(x)) y else x

# -----------------------------------------------------------------------------
# Config file writer
# -----------------------------------------------------------------------------

#' Known keys for `_business-report-config.typ`
#' @noRd
.config_keys <- c(
  "font-family",
  "primary-color",
  "toc-style",
  "cover",
  "cover-image",
  "cover-title-color",
  "cover-title-x",
  "cover-title-y",
  "back-cover",
  "lang"
)

#' Validate a scalar logical flag
#' @noRd
.check_flag <- function(value, arg_name) {
  if (!is.logical(value) || length(value) != 1L || is.na(value)) {
    cli::cli_abort("{.arg {arg_name}} must be TRUE or FALSE.")
  }

  value
}

#' Convert an R logical into Typst boolean syntax
#' @noRd
.bool_to_typst <- function(value) {
  if (.check_flag(value, "value")) "true" else "false"
}

#' Wrap a scalar string as a Typst string literal
#' @noRd
.typst_string <- function(value) {
  glue::glue('"{value}"')
}

#' Assemble config values in a consistent structure
#' @noRd
.build_config_values <- function(
  font_family,
  primary_color,
  toc_style,
  cover,
  cover_image,
  cover_title_color,
  cover_title_x,
  cover_title_y,
  back_cover,
  lang
) {
  list(
    "font-family" = .typst_string(font_family),
    "primary-color" = glue::glue('rgb("{primary_color}")'),
    "toc-style" = as.character(as.integer(toc_style)),
    "cover" = .bool_to_typst(cover),
    "cover-image" = if (is.null(cover_image)) "none" else .typst_string(cover_image),
    "cover-title-color" = glue::glue('rgb("{cover_title_color}")'),
    "cover-title-x" = cover_title_x,
    "cover-title-y" = cover_title_y,
    "back-cover" = .bool_to_typst(back_cover),
    "lang" = .typst_string(lang)
  )
}

#' Convert config values into standardized Typst lines
#' @noRd
.config_lines_from_values <- function(values) {
  c(
    "// _business-report-config.typ",
    "// Generated by the BusinessReport R package - edit directly or regenerate with",
    "// BusinessReport::set_font(), BusinessReport::set_toc_style(), etc.",
    "//",
    "// ------------------------------------------------------------------------",
    "",
    "#let business-config = (",
    glue::glue("  font-family:       {values[['font-family']]},"),
    glue::glue("  primary-color:     {values[['primary-color']]},"),
    glue::glue("  toc-style:         {values[['toc-style']]},"),
    glue::glue("  cover:             {values[['cover']]},"),
    glue::glue("  cover-image:       {values[['cover-image']]},"),
    glue::glue("  cover-title-color: {values[['cover-title-color']]},"),
    glue::glue("  cover-title-x:     {values[['cover-title-x']]},"),
    glue::glue("  cover-title-y:     {values[['cover-title-y']]},"),
    glue::glue("  back-cover:        {values[['back-cover']]},"),
    glue::glue("  lang:              {values[['lang']]},"),
    ")"
  )
}

#' Write config values back to `_business-report-config.typ`
#' @noRd
.write_config_values <- function(path, values) {
  missing_keys <- setdiff(.config_keys, names(values))
  if (length(missing_keys) > 0L) {
    cli::cli_abort(
      "Missing config keys in {.file _business-report-config.typ}: {.val {missing_keys}}."
    )
  }

  writeLines(.config_lines_from_values(values), .config_typ_path(path))
  invisible(path)
}

#' Write or overwrite `_business-report-config.typ` in the project extension dir
#'
#' @param path Project root.
#' @param font_family  Typst font family string.
#' @param primary_color  Hex colour string (with leading `#`).
#' @param toc_style  Integer 1-4.
#' @param cover  Logical.
#' @param cover_image  Relative or absolute cover image path for Typst.
#' @param cover_title_color  Cover title color as hex string.
#' @param cover_title_x  Horizontal offset for the cover title in Typst units.
#' @param cover_title_y  Vertical offset for the cover title in Typst units.
#' @param back_cover  Logical.
#' @param lang  BCP 47 language tag string.
#' @noRd
.write_config <- function(
  path,
  font_family   = "Georgia",
  primary_color = "#1a3a5c",
  toc_style     = 1L,
  cover         = TRUE,
  cover_image   = NULL,
  cover_title_color = "#FFFFFF",
  cover_title_x = "18mm",
  cover_title_y = "110mm",
  back_cover    = TRUE,
  lang          = "pt"
) {
  values <- .build_config_values(
    font_family = font_family,
    primary_color = primary_color,
    toc_style = toc_style,
    cover = cover,
    cover_image = cover_image,
    cover_title_color = cover_title_color,
    cover_title_x = cover_title_x,
    cover_title_y = cover_title_y,
    back_cover = back_cover,
    lang = lang
  )

  .write_config_values(path, values)
  invisible(.config_typ_path(path))
}

# -----------------------------------------------------------------------------
# Config file reader (line-level regex updates)
# -----------------------------------------------------------------------------

#' Read the config Typst file as a character vector
#' @noRd
.read_config_lines <- function(path) {
  cfg <- .config_typ_path(path)
  if (!fs::file_exists(cfg)) {
    cli::cli_abort(
      c(
        "No {.file _business-report-config.typ} found at {.path {cfg}}.",
        "i" = "Run {.fn BusinessReport::create_business_report} first."
      )
    )
  }
  readLines(cfg, warn = FALSE)
}

#' Parse `_business-report-config.typ` into a named list of raw Typst values
#'
#' @noRd
.read_config_values <- function(path) {
  lines <- .read_config_lines(path)
  values <- list()
  pattern <- "^\\s*([A-Za-z-]+):\\s*(.+),\\s*$"

  for (line in lines) {
    captures <- regmatches(line, regexec(pattern, line))[[1L]]
    if (length(captures) != 3L) {
      next
    }

    key <- captures[[2L]]
    if (!key %in% .config_keys) {
      next
    }

    values[[key]] <- captures[[3L]]
  }

  missing_keys <- setdiff(.config_keys, names(values))
  if (length(missing_keys) > 0L) {
    cli::cli_abort(
      c(
        "Incomplete {.file _business-report-config.typ} in {.path {path}}.",
        "i" = "Missing keys: {.val {missing_keys}}."
      )
    )
  }

  values[.config_keys]
}

#' Replace a config value and rewrite the config file in a normalized format
#'
#' @param path  Project root.
#' @param key   Config key name as it appears in the Typst file.
#' @param new_value  Replacement value string (Typst syntax, without trailing comma).
#' @noRd
.update_config_key <- function(path, key, new_value) {
  values <- .read_config_values(path)

  if (!key %in% names(values)) {
    cli::cli_abort("Key {.val {key}} not found in {.file _business-report-config.typ}.")
  }

  values[[key]] <- new_value
  .write_config_values(path, values)
  invisible(path)
}

#' Emit a standardized success message for config updates
#'
#' @param success_message Message shown as the main success output.
#' @param rerender Logical. Whether to append a re-render reminder.
#' @param .envir Environment used to resolve cli inline expressions.
#' @noRd
.inform_config_update <- function(
  success_message,
  rerender = TRUE,
  .envir = parent.frame()
) {
  message <- c("v" = success_message)

  if (.check_flag(rerender, "rerender")) {
    message <- c(
      message,
      "i" = "Re-renderize seu arquivo {.file .qmd} para ver a mudanca."
    )
  }

  cli::cli_inform(message, .envir = .envir)
}

# -----------------------------------------------------------------------------
# Input validation helpers
# -----------------------------------------------------------------------------

#' Check that a toc_style argument is valid (1, 2, 3, or 4)
#' @noRd
.check_toc_style <- function(style) {
  style <- suppressWarnings(as.integer(style))
  if (is.na(style) || !style %in% 1L:4L) {
    cli::cli_abort(
      c(
        "{.arg toc_style} must be an integer between 1 and 4.",
        "i" = "Use {.fn BusinessReport::list_toc_styles} to see available styles."
      )
    )
  }
  style
}

#' Check that a hex colour is plausibly valid
#' @noRd
.check_color <- function(color) {
  if (!grepl("^#[0-9A-Fa-f]{6}$", color)) {
    cli::cli_abort(
      "{.arg primary_color} must be a six-digit hex colour, e.g. {.val #1a3a5c}."
    )
  }
  color
}

#' Check that a font ID is in the registry
#' @noRd
.check_font_id <- function(font) {
  registry <- list_fonts()
  if (!font %in% registry[["id"]]) {
    cli::cli_abort(
      c(
        "{.val {font}} is not a recognised font id.",
        "i" = "Use {.fn BusinessReport::list_fonts} to see available fonts."
      )
    )
  }
  registry[registry[["id"]] == font, "typst_family"][[1L]]
}

#' Normalise an optional cover image path for Typst config
#' @noRd
.normalize_cover_image_path <- function(path) {
  if (is.null(path)) {
    return(NULL)
  }

  if (!is.character(path) || length(path) != 1L || is.na(path)) {
    cli::cli_abort("{.arg cover_image} must be a single character string or NULL.")
  }

  trimmed <- trimws(path)
  if (!nzchar(trimmed)) {
    return(NULL)
  }

  normalised <- gsub("\\\\", "/", trimmed)
  if (grepl("^[A-Za-z]:/", normalised) || grepl("^/", normalised)) {
    return(normalised)
  }

  relative_path <- fs::path("..", "..", normalised) |> as.character()
  gsub("\\\\", "/", relative_path)
}

#' Normalise a Typst length token
#' @noRd
.normalize_typst_length <- function(value, arg_name) {
  if (!is.character(value) || length(value) != 1L || is.na(value)) {
    cli::cli_abort("{.arg {arg_name}} must be a single character string.")
  }

  trimmed <- trimws(value)
  pattern <- "^-?[0-9]+(\\.[0-9]+)?(pt|mm|cm|in|em|rem)$"
  if (!grepl(pattern, trimmed)) {
    cli::cli_abort(
      c(
        "{.arg {arg_name}} must be a Typst length like {.val 18mm} or {.val 24pt}."
      )
    )
  }

  trimmed
}
