# R/utils.R
# Internal utility functions - not exported

# -----------------------------------------------------------------------------
# Path helpers
# -----------------------------------------------------------------------------

#' Return the path to the bundled Quarto extension source
#' @noRd
.ext_source <- function() {
  system.file(
    "quarto", "_extensions", "business-report",
    package = "BusinessReport",
    mustWork = TRUE
  )
}

#' Return the path to the extension inside a user project
#' @noRd
.ext_dest <- function(path) {
  fs::path(path, "_extensions", "business-report")
}

#' Return the path to the config Typst file inside a user project
#' @noRd
.config_typ_path <- function(path) {
  fs::path(.ext_dest(path), "_business-report-config.typ")
}

#' Return the path to the skeleton template
#' @noRd
.skeleton_path <- function() {
  system.file(
    "templates", "skeleton.qmd",
    package = "BusinessReport",
    mustWork = TRUE
  )
}

#' Return the path to the assets template directory
#' @noRd
.assets_source <- function() {
  system.file("templates", "assets", package = "BusinessReport", mustWork = TRUE)
}

# -----------------------------------------------------------------------------
# Config file writer
# -----------------------------------------------------------------------------

#' Write or overwrite `_business-report-config.typ` in the project extension dir
#'
#' @param path Project root.
#' @param font_family  Typst font family string.
#' @param primary_color  Hex colour string (with leading `#`).
#' @param toc_style  Integer 1-3.
#' @param cover  Logical.
#' @param cover_image  Relative or absolute cover image path for Typst.
#' @param cover_title_color  Cover title color as hex string.
#' @param cover_title_x  Horizontal offset for the cover title in Typst units.
#' @param cover_title_y  Vertical offset for the cover title in Typst units.
#' @param back_cover  Logical.
#' @param lang  BCP 47 language tag string.
#' @noRd
.write_config <- function(
  path,
  font_family   = "Georgia",
  primary_color = "#1a3a5c",
  toc_style     = 1L,
  cover         = TRUE,
  cover_image   = NULL,
  cover_title_color = "#FFFFFF",
  cover_title_x = "18mm",
  cover_title_y = "110mm",
  back_cover    = TRUE,
  lang          = "pt"
) {
  config_path <- .config_typ_path(path)

  bool_str <- function(x) if (isTRUE(x)) "true" else "false"

  lines <- c(
    "// _business-report-config.typ",
    "// Generated by the BusinessReport R package - edit directly or regenerate with",
    "// BusinessReport::set_font(), BusinessReport::set_toc_style(), etc.",
    "//",
    "// ------------------------------------------------------------------------",
    "",
    "#let business-config = (",
    glue::glue('  font-family:   "{font_family}",'),
    glue::glue('  primary-color: rgb("{primary_color}"),'),
    glue::glue("  toc-style:     {as.integer(toc_style)},"),
    glue::glue("  cover:         {bool_str(cover)},"),
    glue::glue('  cover-image:   {if (is.null(cover_image)) "none" else paste0(\'"\', cover_image, \'"\')},'),
    glue::glue('  cover-title-color: rgb("{cover_title_color}"),'),
    glue::glue("  cover-title-x: {cover_title_x},"),
    glue::glue("  cover-title-y: {cover_title_y},"),
    glue::glue("  back-cover:    {bool_str(back_cover)},"),
    glue::glue('  lang:          "{lang}",'),
    ")"
  )

  writeLines(lines, config_path)
  invisible(config_path)
}

# -----------------------------------------------------------------------------
# Config file reader (line-level regex updates)
# -----------------------------------------------------------------------------

#' Read the config Typst file as a character vector
#' @noRd
.read_config_lines <- function(path) {
  cfg <- .config_typ_path(path)
  if (!fs::file_exists(cfg)) {
    cli::cli_abort(
      c(
        "No {.file _business-report-config.typ} found at {.path {cfg}}.",
        "i" = "Run {.fn BusinessReport::create_business_report} first."
      )
    )
  }
  readLines(cfg, warn = FALSE)
}

#' Replace a key=value line in the config Typst file
#'
#' Targets lines of the form `  key:  <value>,` and replaces the value part.
#'
#' @param path  Project root.
#' @param key   Config key name as it appears in the Typst file.
#' @param new_value  Replacement value string (Typst syntax, without trailing comma).
#' @noRd
.update_config_key <- function(path, key, new_value) {
  lines <- .read_config_lines(path)
  pattern <- paste0("^(\\s+", key, ":\\s+)(.+)(,)$")
  idx <- grep(pattern, lines)

  if (length(idx) == 0L) {
    cli::cli_abort("Key {.val {key}} not found in {.file _business-report-config.typ}.")
  }

  lines[idx] <- sub(pattern, paste0("\\1", new_value, "\\3"), lines[idx])
  writeLines(lines, .config_typ_path(path))
  invisible(path)
}

# -----------------------------------------------------------------------------
# Input validation helpers
# -----------------------------------------------------------------------------

#' Check that a toc_style argument is valid (1, 2, 3, or 4)
#' @noRd
.check_toc_style <- function(style) {
  style <- suppressWarnings(as.integer(style))
  if (is.na(style) || !style %in% 1L:4L) {
    cli::cli_abort(
      c(
        "{.arg toc_style} must be an integer between 1 and 4.",
        "i" = "Use {.fn BusinessReport::list_toc_styles} to see available styles."
      )
    )
  }
  style
}

#' Check that a hex colour is plausibly valid
#' @noRd
.check_color <- function(color) {
  if (!grepl("^#[0-9A-Fa-f]{6}$", color)) {
    cli::cli_abort(
      "{.arg primary_color} must be a six-digit hex colour, e.g. {.val #1a3a5c}."
    )
  }
  color
}

#' Check that a font ID is in the registry
#' @noRd
.check_font_id <- function(font) {
  registry <- list_fonts()
  if (!font %in% registry[["id"]]) {
    cli::cli_abort(
      c(
        "{.val {font}} is not a recognised font id.",
        "i" = "Use {.fn BusinessReport::list_fonts} to see available fonts."
      )
    )
  }
  registry[registry[["id"]] == font, "typst_family"][[1L]]
}

#' Normalise an optional cover image path for Typst config
#' @noRd
.normalize_cover_image_path <- function(path) {
  if (is.null(path)) {
    return(NULL)
  }

  if (!is.character(path) || length(path) != 1L || is.na(path)) {
    cli::cli_abort("{.arg cover_image} must be a single character string or NULL.")
  }

  trimmed <- trimws(path)
  if (!nzchar(trimmed)) {
    return(NULL)
  }

  normalised <- gsub("\\\\", "/", trimmed)
  if (grepl("^[A-Za-z]:/", normalised) || grepl("^/", normalised)) {
    return(normalised)
  }

  relative_path <- fs::path("..", "..", normalised) |> as.character()
  gsub("\\\\", "/", relative_path)
}

#' Normalise a Typst length token
#' @noRd
.normalize_typst_length <- function(value, arg_name) {
  if (!is.character(value) || length(value) != 1L || is.na(value)) {
    cli::cli_abort("{.arg {arg_name}} must be a single character string.")
  }

  trimmed <- trimws(value)
  pattern <- "^-?[0-9]+(\\.[0-9]+)?(pt|mm|cm|in|em|rem)$"
  if (!grepl(pattern, trimmed)) {
    cli::cli_abort(
      c(
        "{.arg {arg_name}} must be a Typst length like {.val 18mm} or {.val 24pt}."
      )
    )
  }

  trimmed
}
